generator:
  class: sfPropelGenerator
  param:
    model_class:           Command
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Command
    plural:                Commands
    route_prefix:          command
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
